#pragma once
#define MAINMENU -1
#define PLAY 0
#define PRACTICE 1
#define HIGHSCORE 2
#define SETTINGS 3
#define EXIT 4

#define TITLE_X_OFFSET 31
#define TITLE_Y_OFFSET 5

#define PLAY_X_OFFSET 38
#define PLAY_Y_OFFSET 15

#define PRACTICE_X_OFFSET 36
#define PRACTICE_Y_OFFSET 17

#define HIGH_SCORES_X_OFFSET 35
#define HIGH_SCORES_Y_OFFSET 19

#define SETTINGS_X_OFFSET 36
#define SETTINGS_Y_OFFSET 21

#define EXIT_X_OFFSET 38
#define EXIT_Y_OFFSET 23

#define MAX_DELAY_NUM 10
#define STAR_DELAY 3
#define CURSOR_DELAY 30
#define INPUT_DELAY 7
